version: '3.7'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 9090:9090
    volumes:
      - /tmp:/var/lib/app
    depends_on:
      - pgsql

  pgsql:
    container_name: pgsql
    image: postgres:latest
    environment:
      POSTGRES_DB: base-project-spring-webflux-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: rhribeiro_25@hotmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - 16543:80
    depends_on:
      - pgsql

networks:
  default:
    external:
      name: base-project-spring-webflux-net